services:
    catalogdb:
        container_name: catalogdb
        environment:
            - POSTGRES_DB=CatalogDb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        restart: allways 
        ports:
            - "5432:5432"
        volumes:
            - postgres_catalog:/var/lib/postgresql/data/    